// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using University_Admission.Data;

#nullable disable

namespace University_Admission.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250604064925_ChangePasswordLength")]
    partial class ChangePasswordLength
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("University_Admission.Domain.Entities.CommonEntities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("DialCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "AFG",
                            DialCode = "93",
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Id = 2,
                            Code = "ALB",
                            DialCode = "355",
                            Name = "Albania"
                        },
                        new
                        {
                            Id = 3,
                            Code = "DZA",
                            DialCode = "213",
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = 4,
                            Code = "ASM",
                            DialCode = "1-684",
                            Name = "American Samoa"
                        },
                        new
                        {
                            Id = 5,
                            Code = "AND",
                            DialCode = "376",
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = 6,
                            Code = "AGO",
                            DialCode = "244",
                            Name = "Angola"
                        },
                        new
                        {
                            Id = 7,
                            Code = "AIA",
                            DialCode = "1-264",
                            Name = "Anguilla"
                        },
                        new
                        {
                            Id = 8,
                            Code = "ATA",
                            DialCode = "672",
                            Name = "Antarctica"
                        },
                        new
                        {
                            Id = 9,
                            Code = "ATG",
                            DialCode = "1-268",
                            Name = "Antigua and Barbuda"
                        },
                        new
                        {
                            Id = 10,
                            Code = "ARG",
                            DialCode = "54",
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = 11,
                            Code = "ARM",
                            DialCode = "374",
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = 12,
                            Code = "ABW",
                            DialCode = "297",
                            Name = "Aruba"
                        },
                        new
                        {
                            Id = 13,
                            Code = "AUS",
                            DialCode = "61",
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 14,
                            Code = "AUT",
                            DialCode = "43",
                            Name = "Austria"
                        },
                        new
                        {
                            Id = 15,
                            Code = "AZE",
                            DialCode = "994",
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Id = 16,
                            Code = "BHS",
                            DialCode = "1-242",
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = 17,
                            Code = "BHR",
                            DialCode = "973",
                            Name = "Bahrain"
                        },
                        new
                        {
                            Id = 18,
                            Code = "BGD",
                            DialCode = "880",
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = 19,
                            Code = "BRB",
                            DialCode = "1-246",
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = 20,
                            Code = "BLR",
                            DialCode = "375",
                            Name = "Belarus"
                        },
                        new
                        {
                            Id = 21,
                            Code = "BEL",
                            DialCode = "32",
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = 22,
                            Code = "BLZ",
                            DialCode = "501",
                            Name = "Belize"
                        },
                        new
                        {
                            Id = 23,
                            Code = "BEN",
                            DialCode = "229",
                            Name = "Benin"
                        },
                        new
                        {
                            Id = 24,
                            Code = "BMU",
                            DialCode = "1-441",
                            Name = "Bermuda"
                        },
                        new
                        {
                            Id = 25,
                            Code = "BTN",
                            DialCode = "975",
                            Name = "Bhutan"
                        },
                        new
                        {
                            Id = 26,
                            Code = "BOL",
                            DialCode = "591",
                            Name = "Bolivia"
                        },
                        new
                        {
                            Id = 27,
                            Code = "BIH",
                            DialCode = "387",
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            Id = 28,
                            Code = "BWA",
                            DialCode = "267",
                            Name = "Botswana"
                        },
                        new
                        {
                            Id = 29,
                            Code = "BRA",
                            DialCode = "55",
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = 30,
                            Code = "IOT",
                            DialCode = "246",
                            Name = "British Indian Ocean Territory"
                        },
                        new
                        {
                            Id = 31,
                            Code = "VGB",
                            DialCode = "1-284",
                            Name = "British Virgin Islands"
                        },
                        new
                        {
                            Id = 32,
                            Code = "BRN",
                            DialCode = "673",
                            Name = "Brunei"
                        },
                        new
                        {
                            Id = 33,
                            Code = "BGR",
                            DialCode = "359",
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = 34,
                            Code = "BFA",
                            DialCode = "226",
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            Id = 35,
                            Code = "BDI",
                            DialCode = "257",
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = 36,
                            Code = "KHM",
                            DialCode = "855",
                            Name = "Cambodia"
                        },
                        new
                        {
                            Id = 37,
                            Code = "CMR",
                            DialCode = "237",
                            Name = "Cameroon"
                        },
                        new
                        {
                            Id = 38,
                            Code = "CAN",
                            DialCode = "1",
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 39,
                            Code = "CPV",
                            DialCode = "238",
                            Name = "Cape Verde"
                        },
                        new
                        {
                            Id = 40,
                            Code = "CYM",
                            DialCode = "1-345",
                            Name = "Cayman Islands"
                        },
                        new
                        {
                            Id = 41,
                            Code = "CAF",
                            DialCode = "236",
                            Name = "Central African Republic"
                        },
                        new
                        {
                            Id = 42,
                            Code = "TCD",
                            DialCode = "235",
                            Name = "Chad"
                        },
                        new
                        {
                            Id = 43,
                            Code = "CHL",
                            DialCode = "56",
                            Name = "Chile"
                        },
                        new
                        {
                            Id = 44,
                            Code = "CHN",
                            DialCode = "86",
                            Name = "China"
                        },
                        new
                        {
                            Id = 45,
                            Code = "CXR",
                            DialCode = "61",
                            Name = "Christmas Island"
                        },
                        new
                        {
                            Id = 46,
                            Code = "CCK",
                            DialCode = "61",
                            Name = "Cocos Islands"
                        },
                        new
                        {
                            Id = 47,
                            Code = "COL",
                            DialCode = "57",
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = 48,
                            Code = "COM",
                            DialCode = "269",
                            Name = "Comoros"
                        },
                        new
                        {
                            Id = 49,
                            Code = "COK",
                            DialCode = "682",
                            Name = "Cook Islands"
                        },
                        new
                        {
                            Id = 50,
                            Code = "CRI",
                            DialCode = "506",
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = 51,
                            Code = "HRV",
                            DialCode = "385",
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = 52,
                            Code = "CUB",
                            DialCode = "53",
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = 53,
                            Code = "CUW",
                            DialCode = "599",
                            Name = "Curacao"
                        },
                        new
                        {
                            Id = 54,
                            Code = "CYP",
                            DialCode = "357",
                            Name = "Cyprus"
                        },
                        new
                        {
                            Id = 55,
                            Code = "CZE",
                            DialCode = "420",
                            Name = "Czech Republic"
                        },
                        new
                        {
                            Id = 56,
                            Code = "COD",
                            DialCode = "243",
                            Name = "Democratic Republic of the Congo"
                        },
                        new
                        {
                            Id = 57,
                            Code = "DNK",
                            DialCode = "45",
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = 58,
                            Code = "DJI",
                            DialCode = "253",
                            Name = "Djibouti"
                        },
                        new
                        {
                            Id = 59,
                            Code = "DMA",
                            DialCode = "1-767",
                            Name = "Dominica"
                        },
                        new
                        {
                            Id = 60,
                            Code = "DOM",
                            DialCode = "1-809, 1-829, 1-849",
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            Id = 61,
                            Code = "TLS",
                            DialCode = "670",
                            Name = "East Timor"
                        },
                        new
                        {
                            Id = 62,
                            Code = "ECU",
                            DialCode = "593",
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = 63,
                            Code = "EGY",
                            DialCode = "20",
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = 64,
                            Code = "SLV",
                            DialCode = "503",
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = 65,
                            Code = "GNQ",
                            DialCode = "240",
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            Id = 66,
                            Code = "ERI",
                            DialCode = "291",
                            Name = "Eritrea"
                        },
                        new
                        {
                            Id = 67,
                            Code = "EST",
                            DialCode = "372",
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = 68,
                            Code = "ETH",
                            DialCode = "251",
                            Name = "Ethiopia"
                        },
                        new
                        {
                            Id = 69,
                            Code = "FLK",
                            DialCode = "500",
                            Name = "Falkland Islands"
                        },
                        new
                        {
                            Id = 70,
                            Code = "FRO",
                            DialCode = "298",
                            Name = "Faroe Islands"
                        },
                        new
                        {
                            Id = 71,
                            Code = "FJI",
                            DialCode = "679",
                            Name = "Fiji"
                        },
                        new
                        {
                            Id = 72,
                            Code = "FIN",
                            DialCode = "358",
                            Name = "Finland"
                        },
                        new
                        {
                            Id = 73,
                            Code = "FRA",
                            DialCode = "33",
                            Name = "France"
                        },
                        new
                        {
                            Id = 74,
                            Code = "PYF",
                            DialCode = "689",
                            Name = "French Polynesia"
                        },
                        new
                        {
                            Id = 75,
                            Code = "GAB",
                            DialCode = "241",
                            Name = "Gabon"
                        },
                        new
                        {
                            Id = 76,
                            Code = "GMB",
                            DialCode = "220",
                            Name = "Gambia"
                        },
                        new
                        {
                            Id = 77,
                            Code = "GEO",
                            DialCode = "995",
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = 78,
                            Code = "DEU",
                            DialCode = "49",
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 79,
                            Code = "GHA",
                            DialCode = "233",
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = 80,
                            Code = "GIB",
                            DialCode = "350",
                            Name = "Gibraltar"
                        },
                        new
                        {
                            Id = 81,
                            Code = "GRC",
                            DialCode = "30",
                            Name = "Greece"
                        },
                        new
                        {
                            Id = 82,
                            Code = "GRL",
                            DialCode = "299",
                            Name = "Greenland"
                        },
                        new
                        {
                            Id = 83,
                            Code = "GRD",
                            DialCode = "1-473",
                            Name = "Grenada"
                        },
                        new
                        {
                            Id = 84,
                            Code = "GUM",
                            DialCode = "1-671",
                            Name = "Guam"
                        },
                        new
                        {
                            Id = 85,
                            Code = "GTM",
                            DialCode = "502",
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = 86,
                            Code = "GGY",
                            DialCode = "44-1481",
                            Name = "Guernsey"
                        },
                        new
                        {
                            Id = 87,
                            Code = "GIN",
                            DialCode = "224",
                            Name = "Guinea"
                        },
                        new
                        {
                            Id = 88,
                            Code = "GNB",
                            DialCode = "245",
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = 89,
                            Code = "GUY",
                            DialCode = "592",
                            Name = "Guyana"
                        },
                        new
                        {
                            Id = 90,
                            Code = "HTI",
                            DialCode = "509",
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = 91,
                            Code = "HND",
                            DialCode = "504",
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = 92,
                            Code = "HKG",
                            DialCode = "852",
                            Name = "Hong Kong"
                        },
                        new
                        {
                            Id = 93,
                            Code = "HUN",
                            DialCode = "36",
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = 94,
                            Code = "ISL",
                            DialCode = "354",
                            Name = "Iceland"
                        },
                        new
                        {
                            Id = 95,
                            Code = "IND",
                            DialCode = "91",
                            Name = "India"
                        },
                        new
                        {
                            Id = 96,
                            Code = "IDN",
                            DialCode = "62",
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = 97,
                            Code = "IRN",
                            DialCode = "98",
                            Name = "Iran"
                        },
                        new
                        {
                            Id = 98,
                            Code = "IRQ",
                            DialCode = "964",
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = 99,
                            Code = "IRL",
                            DialCode = "353",
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = 100,
                            Code = "IMN",
                            DialCode = "44-1624",
                            Name = "Isle of Man"
                        },
                        new
                        {
                            Id = 101,
                            Code = "ISR",
                            DialCode = "972",
                            Name = "Israel"
                        },
                        new
                        {
                            Id = 102,
                            Code = "ITA",
                            DialCode = "39",
                            Name = "Italy"
                        },
                        new
                        {
                            Id = 103,
                            Code = "CIV",
                            DialCode = "225",
                            Name = "Ivory Coast"
                        },
                        new
                        {
                            Id = 104,
                            Code = "JAM",
                            DialCode = "1-876",
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = 105,
                            Code = "JPN",
                            DialCode = "81",
                            Name = "Japan"
                        },
                        new
                        {
                            Id = 106,
                            Code = "JEY",
                            DialCode = "44-1534",
                            Name = "Jersey"
                        },
                        new
                        {
                            Id = 107,
                            Code = "JOR",
                            DialCode = "962",
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = 108,
                            Code = "KAZ",
                            DialCode = "7",
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Id = 109,
                            Code = "KEN",
                            DialCode = "254",
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = 110,
                            Code = "KIR",
                            DialCode = "686",
                            Name = "Kiribati"
                        },
                        new
                        {
                            Id = 111,
                            Code = "XKX",
                            DialCode = "383",
                            Name = "Kosovo"
                        },
                        new
                        {
                            Id = 112,
                            Code = "KWT",
                            DialCode = "965",
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = 113,
                            Code = "KGZ",
                            DialCode = "996",
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = 114,
                            Code = "LAO",
                            DialCode = "856",
                            Name = "Laos"
                        },
                        new
                        {
                            Id = 115,
                            Code = "LVA",
                            DialCode = "371",
                            Name = "Latvia"
                        },
                        new
                        {
                            Id = 116,
                            Code = "LBN",
                            DialCode = "961",
                            Name = "Lebanon"
                        },
                        new
                        {
                            Id = 117,
                            Code = "LSO",
                            DialCode = "266",
                            Name = "Lesotho"
                        },
                        new
                        {
                            Id = 118,
                            Code = "LBR",
                            DialCode = "231",
                            Name = "Liberia"
                        },
                        new
                        {
                            Id = 119,
                            Code = "LBY",
                            DialCode = "218",
                            Name = "Libya"
                        },
                        new
                        {
                            Id = 120,
                            Code = "LIE",
                            DialCode = "423",
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = 121,
                            Code = "LTU",
                            DialCode = "370",
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = 122,
                            Code = "LUX",
                            DialCode = "352",
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Id = 123,
                            Code = "MAC",
                            DialCode = "853",
                            Name = "Macau"
                        },
                        new
                        {
                            Id = 124,
                            Code = "MKD",
                            DialCode = "389",
                            Name = "Macedonia"
                        },
                        new
                        {
                            Id = 125,
                            Code = "MDG",
                            DialCode = "261",
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = 126,
                            Code = "MWI",
                            DialCode = "265",
                            Name = "Malawi"
                        },
                        new
                        {
                            Id = 127,
                            Code = "MYS",
                            DialCode = "60",
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = 128,
                            Code = "MDV",
                            DialCode = "960",
                            Name = "Maldives"
                        },
                        new
                        {
                            Id = 129,
                            Code = "MLI",
                            DialCode = "223",
                            Name = "Mali"
                        },
                        new
                        {
                            Id = 130,
                            Code = "MLT",
                            DialCode = "356",
                            Name = "Malta"
                        },
                        new
                        {
                            Id = 131,
                            Code = "MHL",
                            DialCode = "692",
                            Name = "Marshall Islands"
                        },
                        new
                        {
                            Id = 132,
                            Code = "MRT",
                            DialCode = "222",
                            Name = "Mauritania"
                        },
                        new
                        {
                            Id = 133,
                            Code = "MUS",
                            DialCode = "230",
                            Name = "Mauritius"
                        },
                        new
                        {
                            Id = 134,
                            Code = "MYT",
                            DialCode = "262",
                            Name = "Mayotte"
                        },
                        new
                        {
                            Id = 135,
                            Code = "MEX",
                            DialCode = "52",
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = 136,
                            Code = "FSM",
                            DialCode = "691",
                            Name = "Micronesia"
                        },
                        new
                        {
                            Id = 137,
                            Code = "MDA",
                            DialCode = "373",
                            Name = "Moldova"
                        },
                        new
                        {
                            Id = 138,
                            Code = "MCO",
                            DialCode = "377",
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = 139,
                            Code = "MNG",
                            DialCode = "976",
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = 140,
                            Code = "MNE",
                            DialCode = "382",
                            Name = "Montenegro"
                        },
                        new
                        {
                            Id = 141,
                            Code = "MSR",
                            DialCode = "1-664",
                            Name = "Montserrat"
                        },
                        new
                        {
                            Id = 142,
                            Code = "MAR",
                            DialCode = "212",
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = 143,
                            Code = "MOZ",
                            DialCode = "258",
                            Name = "Mozambique"
                        },
                        new
                        {
                            Id = 144,
                            Code = "MMR",
                            DialCode = "95",
                            Name = "Myanmar"
                        },
                        new
                        {
                            Id = 145,
                            Code = "NAM",
                            DialCode = "264",
                            Name = "Namibia"
                        },
                        new
                        {
                            Id = 146,
                            Code = "NRU",
                            DialCode = "674",
                            Name = "Nauru"
                        },
                        new
                        {
                            Id = 147,
                            Code = "NPL",
                            DialCode = "977",
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = 148,
                            Code = "NLD",
                            DialCode = "31",
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = 149,
                            Code = "ANT",
                            DialCode = "599",
                            Name = "Netherlands Antilles"
                        },
                        new
                        {
                            Id = 150,
                            Code = "NCL",
                            DialCode = "687",
                            Name = "New Caledonia"
                        },
                        new
                        {
                            Id = 151,
                            Code = "NZL",
                            DialCode = "64",
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = 152,
                            Code = "NIC",
                            DialCode = "505",
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = 153,
                            Code = "NER",
                            DialCode = "227",
                            Name = "Niger"
                        },
                        new
                        {
                            Id = 154,
                            Code = "NGA",
                            DialCode = "234",
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = 155,
                            Code = "NIU",
                            DialCode = "683",
                            Name = "Niue"
                        },
                        new
                        {
                            Id = 156,
                            Code = "PRK",
                            DialCode = "850",
                            Name = "North Korea"
                        },
                        new
                        {
                            Id = 157,
                            Code = "MNP",
                            DialCode = "1-670",
                            Name = "Northern Mariana Islands"
                        },
                        new
                        {
                            Id = 158,
                            Code = "NOR",
                            DialCode = "47",
                            Name = "Norway"
                        },
                        new
                        {
                            Id = 159,
                            Code = "OMN",
                            DialCode = "968",
                            Name = "Oman"
                        },
                        new
                        {
                            Id = 160,
                            Code = "PAK",
                            DialCode = "92",
                            Name = "Pakistan"
                        },
                        new
                        {
                            Id = 161,
                            Code = "PLW",
                            DialCode = "680",
                            Name = "Palau"
                        },
                        new
                        {
                            Id = 162,
                            Code = "PSE",
                            DialCode = "970",
                            Name = "Palestine"
                        },
                        new
                        {
                            Id = 163,
                            Code = "PAN",
                            DialCode = "507",
                            Name = "Panama"
                        },
                        new
                        {
                            Id = 164,
                            Code = "PNG",
                            DialCode = "675",
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            Id = 165,
                            Code = "PRY",
                            DialCode = "595",
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = 166,
                            Code = "PER",
                            DialCode = "51",
                            Name = "Peru"
                        },
                        new
                        {
                            Id = 167,
                            Code = "PHL",
                            DialCode = "63",
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = 168,
                            Code = "PCN",
                            DialCode = "64",
                            Name = "Pitcairn"
                        },
                        new
                        {
                            Id = 169,
                            Code = "POL",
                            DialCode = "48",
                            Name = "Poland"
                        },
                        new
                        {
                            Id = 170,
                            Code = "PRT",
                            DialCode = "351",
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = 171,
                            Code = "PRI",
                            DialCode = "1-787, 1-939",
                            Name = "Puerto Rico"
                        },
                        new
                        {
                            Id = 172,
                            Code = "QAT",
                            DialCode = "974",
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = 173,
                            Code = "COG",
                            DialCode = "242",
                            Name = "Republic of the Congo"
                        },
                        new
                        {
                            Id = 174,
                            Code = "REU",
                            DialCode = "262",
                            Name = "Reunion"
                        },
                        new
                        {
                            Id = 175,
                            Code = "ROU",
                            DialCode = "40",
                            Name = "Romania"
                        },
                        new
                        {
                            Id = 176,
                            Code = "RUS",
                            DialCode = "7",
                            Name = "Russia"
                        },
                        new
                        {
                            Id = 177,
                            Code = "RWA",
                            DialCode = "250",
                            Name = "Rwanda"
                        },
                        new
                        {
                            Id = 178,
                            Code = "BLM",
                            DialCode = "590",
                            Name = "Saint Barthelemy"
                        },
                        new
                        {
                            Id = 179,
                            Code = "SHN",
                            DialCode = "290",
                            Name = "Saint Helena"
                        },
                        new
                        {
                            Id = 180,
                            Code = "KNA",
                            DialCode = "1-869",
                            Name = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            Id = 181,
                            Code = "LCA",
                            DialCode = "1-758",
                            Name = "Saint Lucia"
                        },
                        new
                        {
                            Id = 182,
                            Code = "MAF",
                            DialCode = "590",
                            Name = "Saint Martin"
                        },
                        new
                        {
                            Id = 183,
                            Code = "SPM",
                            DialCode = "508",
                            Name = "Saint Pierre and Miquelon"
                        },
                        new
                        {
                            Id = 184,
                            Code = "VCT",
                            DialCode = "1-784",
                            Name = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            Id = 185,
                            Code = "WSM",
                            DialCode = "685",
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = 186,
                            Code = "SMR",
                            DialCode = "378",
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = 187,
                            Code = "STP",
                            DialCode = "239",
                            Name = "Sao Tome and Principe"
                        },
                        new
                        {
                            Id = 188,
                            Code = "SAU",
                            DialCode = "966",
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = 189,
                            Code = "SEN",
                            DialCode = "221",
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = 190,
                            Code = "SRB",
                            DialCode = "381",
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = 191,
                            Code = "SYC",
                            DialCode = "248",
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = 192,
                            Code = "SLE",
                            DialCode = "232",
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            Id = 193,
                            Code = "SGP",
                            DialCode = "65",
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = 194,
                            Code = "SXM",
                            DialCode = "1-721",
                            Name = "Sint Maarten"
                        },
                        new
                        {
                            Id = 195,
                            Code = "SVK",
                            DialCode = "421",
                            Name = "Slovakia"
                        },
                        new
                        {
                            Id = 196,
                            Code = "SVN",
                            DialCode = "386",
                            Name = "Slovenia"
                        },
                        new
                        {
                            Id = 197,
                            Code = "SLB",
                            DialCode = "677",
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            Id = 198,
                            Code = "SOM",
                            DialCode = "252",
                            Name = "Somalia"
                        },
                        new
                        {
                            Id = 199,
                            Code = "ZAF",
                            DialCode = "27",
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = 200,
                            Code = "KOR",
                            DialCode = "82",
                            Name = "South Korea"
                        },
                        new
                        {
                            Id = 201,
                            Code = "SSD",
                            DialCode = "211",
                            Name = "South Sudan"
                        },
                        new
                        {
                            Id = 202,
                            Code = "ESP",
                            DialCode = "34",
                            Name = "Spain"
                        },
                        new
                        {
                            Id = 203,
                            Code = "LKA",
                            DialCode = "94",
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = 204,
                            Code = "SDN",
                            DialCode = "249",
                            Name = "Sudan"
                        },
                        new
                        {
                            Id = 205,
                            Code = "SUR",
                            DialCode = "597",
                            Name = "Suriname"
                        },
                        new
                        {
                            Id = 206,
                            Code = "SJM",
                            DialCode = "47",
                            Name = "Svalbard and Jan Mayen"
                        },
                        new
                        {
                            Id = 207,
                            Code = "SWZ",
                            DialCode = "268",
                            Name = "Swaziland"
                        },
                        new
                        {
                            Id = 208,
                            Code = "SWE",
                            DialCode = "46",
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = 209,
                            Code = "CHE",
                            DialCode = "41",
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = 210,
                            Code = "SYR",
                            DialCode = "963",
                            Name = "Syria"
                        },
                        new
                        {
                            Id = 211,
                            Code = "TWN",
                            DialCode = "886",
                            Name = "Taiwan"
                        },
                        new
                        {
                            Id = 212,
                            Code = "TJK",
                            DialCode = "992",
                            Name = "Tajikistan"
                        },
                        new
                        {
                            Id = 213,
                            Code = "TZA",
                            DialCode = "255",
                            Name = "Tanzania"
                        },
                        new
                        {
                            Id = 214,
                            Code = "THA",
                            DialCode = "66",
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = 215,
                            Code = "TGO",
                            DialCode = "228",
                            Name = "Togo"
                        },
                        new
                        {
                            Id = 216,
                            Code = "TKL",
                            DialCode = "690",
                            Name = "Tokelau"
                        },
                        new
                        {
                            Id = 217,
                            Code = "TON",
                            DialCode = "676",
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = 218,
                            Code = "TTO",
                            DialCode = "1-868",
                            Name = "Trinidad and Tobago"
                        },
                        new
                        {
                            Id = 219,
                            Code = "TUN",
                            DialCode = "216",
                            Name = "Tunisia"
                        },
                        new
                        {
                            Id = 220,
                            Code = "TUR",
                            DialCode = "90",
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = 221,
                            Code = "TKM",
                            DialCode = "993",
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            Id = 222,
                            Code = "TCA",
                            DialCode = "1-649",
                            Name = "Turks and Caicos Islands"
                        },
                        new
                        {
                            Id = 223,
                            Code = "TUV",
                            DialCode = "688",
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Id = 224,
                            Code = "VIR",
                            DialCode = "1-340",
                            Name = "U.S. Virgin Islands"
                        },
                        new
                        {
                            Id = 225,
                            Code = "UGA",
                            DialCode = "256",
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = 226,
                            Code = "UKR",
                            DialCode = "380",
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = 227,
                            Code = "ARE",
                            DialCode = "971",
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Id = 228,
                            Code = "GBR",
                            DialCode = "44",
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = 229,
                            Code = "USA",
                            DialCode = "1",
                            Name = "United States"
                        },
                        new
                        {
                            Id = 230,
                            Code = "URY",
                            DialCode = "598",
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = 231,
                            Code = "UZB",
                            DialCode = "998",
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Id = 232,
                            Code = "VUT",
                            DialCode = "678",
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Id = 233,
                            Code = "VAT",
                            DialCode = "379",
                            Name = "Vatican"
                        },
                        new
                        {
                            Id = 234,
                            Code = "VEN",
                            DialCode = "58",
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = 235,
                            Code = "VNM",
                            DialCode = "84",
                            Name = "Vietnam"
                        },
                        new
                        {
                            Id = 236,
                            Code = "WLF",
                            DialCode = "681",
                            Name = "Wallis and Futuna"
                        },
                        new
                        {
                            Id = 237,
                            Code = "ESH",
                            DialCode = "212",
                            Name = "Western Sahara"
                        },
                        new
                        {
                            Id = 238,
                            Code = "YEM",
                            DialCode = "967",
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = 239,
                            Code = "ZMB",
                            DialCode = "260",
                            Name = "Zambia"
                        },
                        new
                        {
                            Id = 240,
                            Code = "ZWE",
                            DialCode = "263",
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("University_Admission.Domain.Entities.ProcessEntities.UserProgramProcess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UniversityId")
                        .HasColumnType("integer");

                    b.Property<int>("UniversityProgramId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UniversityId");

                    b.HasIndex("UniversityProgramId");

                    b.HasIndex("UserId");

                    b.ToTable("UserProgramProcesses");
                });

            modelBuilder.Entity("University_Admission.Domain.Entities.ProcessEntities.UserProgramRequirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProgramRequirementId")
                        .HasColumnType("integer");

                    b.Property<int>("UserProgramProcessId")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProgramRequirementId");

                    b.HasIndex("UserProgramProcessId");

                    b.ToTable("UserProgramRequirements");
                });

            modelBuilder.Entity("University_Admission.Domain.Entities.ProgramEntities.ProgramRequirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("UniversityProgramId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UniversityProgramId");

                    b.ToTable("ProgramRequirements");
                });

            modelBuilder.Entity("University_Admission.Domain.Entities.ProgramEntities.University", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("CountryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("WebSite")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Universities");
                });

            modelBuilder.Entity("University_Admission.Domain.Entities.ProgramEntities.UniversityProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Fee")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Level")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("UniversityId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UniversityId");

                    b.ToTable("UniversityPrograms");
                });

            modelBuilder.Entity("University_Admission.Domain.Entities.UserEntities.Announcement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<int>("EntryById")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("Id");

                    b.HasIndex("EntryById");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("University_Admission.Domain.Entities.UserEntities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("University_Admission.Domain.Entities.UserEntities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("NationalityId")
                        .HasColumnType("integer");

                    b.Property<string>("PassportNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("NationalityId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("University_Admission.Domain.Entities.ProcessEntities.UserProgramProcess", b =>
                {
                    b.HasOne("University_Admission.Domain.Entities.ProgramEntities.University", "University")
                        .WithMany()
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("University_Admission.Domain.Entities.ProgramEntities.UniversityProgram", "UniversityProgram")
                        .WithMany()
                        .HasForeignKey("UniversityProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("University_Admission.Domain.Entities.UserEntities.User", "User")
                        .WithMany("Processes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("University");

                    b.Navigation("UniversityProgram");

                    b.Navigation("User");
                });

            modelBuilder.Entity("University_Admission.Domain.Entities.ProcessEntities.UserProgramRequirement", b =>
                {
                    b.HasOne("University_Admission.Domain.Entities.ProgramEntities.ProgramRequirement", "ProgramRequirement")
                        .WithMany()
                        .HasForeignKey("ProgramRequirementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("University_Admission.Domain.Entities.ProcessEntities.UserProgramProcess", "UserProgramProcess")
                        .WithMany("Requirements")
                        .HasForeignKey("UserProgramProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProgramRequirement");

                    b.Navigation("UserProgramProcess");
                });

            modelBuilder.Entity("University_Admission.Domain.Entities.ProgramEntities.ProgramRequirement", b =>
                {
                    b.HasOne("University_Admission.Domain.Entities.ProgramEntities.UniversityProgram", "UniversityProgram")
                        .WithMany("ProgramRequirements")
                        .HasForeignKey("UniversityProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UniversityProgram");
                });

            modelBuilder.Entity("University_Admission.Domain.Entities.ProgramEntities.University", b =>
                {
                    b.HasOne("University_Admission.Domain.Entities.CommonEntities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("University_Admission.Domain.Entities.ProgramEntities.UniversityProgram", b =>
                {
                    b.HasOne("University_Admission.Domain.Entities.ProgramEntities.University", "University")
                        .WithMany("UniversityPrograms")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("University");
                });

            modelBuilder.Entity("University_Admission.Domain.Entities.UserEntities.Announcement", b =>
                {
                    b.HasOne("University_Admission.Domain.Entities.UserEntities.User", "EntryBy")
                        .WithMany("Announcements")
                        .HasForeignKey("EntryById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntryBy");
                });

            modelBuilder.Entity("University_Admission.Domain.Entities.UserEntities.Notification", b =>
                {
                    b.HasOne("University_Admission.Domain.Entities.UserEntities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("University_Admission.Domain.Entities.UserEntities.User", b =>
                {
                    b.HasOne("University_Admission.Domain.Entities.CommonEntities.Country", "Nationality")
                        .WithMany()
                        .HasForeignKey("NationalityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nationality");
                });

            modelBuilder.Entity("University_Admission.Domain.Entities.ProcessEntities.UserProgramProcess", b =>
                {
                    b.Navigation("Requirements");
                });

            modelBuilder.Entity("University_Admission.Domain.Entities.ProgramEntities.University", b =>
                {
                    b.Navigation("UniversityPrograms");
                });

            modelBuilder.Entity("University_Admission.Domain.Entities.ProgramEntities.UniversityProgram", b =>
                {
                    b.Navigation("ProgramRequirements");
                });

            modelBuilder.Entity("University_Admission.Domain.Entities.UserEntities.User", b =>
                {
                    b.Navigation("Announcements");

                    b.Navigation("Notifications");

                    b.Navigation("Processes");
                });
#pragma warning restore 612, 618
        }
    }
}
